DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    cognom VARCHAR(100),
    age INT NOT NULL,
    cicle VARCHAR(100) NOT NULL,
    any_year INT NOT NULL
);
