DROP TABLE IF EXISTS students;

CREATE TABLE students(

    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    cognom VARCHA(100) DEFAULT NULL,
    age INT DEFAULT 0,
    cicle VARCHAR(100) NOT NULL,
    any INT DEFAULT 0
    
);